// Static pointers
pub const STATIC_TEXT_MANAGER_INNER_PTR_OFFSET: u64 = 0x62D5B80;
pub const STATIC_TRADE_CONTRACT_MANAGER_INNER_PTR_OFFST: u64 = 0x62D6E18;

// Functions
pub const STRUCT188_GET_TEXT_OFFSET: u64 = 0x40285E0;
pub const TRADE_CONTRACTS_GET_TRADE_CONTRACTS_OF_ISLAND_OFFSETR: u64 = 0x84CB70;

// Hook vantage points
pub const TRACE_CONTRACT_MANAGER_DO_TRADE_CONTRACT_STUFF_OFFSET: usize = 0x84C4FC;
