use std::fmt::Debug;

#[derive(PartialEq, Eq, Hash, Copy, Clone, Ord, PartialOrd)]
pub struct WareType(pub u32);
pub const BLUEPRINT: WareType = WareType(0x0000_0000);
pub const LOCAL_MAIL: WareType = WareType(0x0000_0217);
pub const REGIONAL_MAIL: WareType = WareType(0x0000_0218);
pub const BAUXITE: WareType = WareType(0x0000_0344);
pub const ALUMINIUM_PROFILES: WareType = WareType(0x0000_0346);
pub const HELIUM: WareType = WareType(0x0000_0348);
pub const WATER_DROP: WareType = WareType(0x0000_0352);
pub const BOMBS: WareType = WareType(0x0000_034e);
pub const SEA_MINES: WareType = WareType(0x0000_034f);
pub const PAMPHLETS: WareType = WareType(0x00000350);
pub const CARE_PACKAGES: WareType = WareType(0x0000_0351);
pub const INDUSTRIAL_LUBRICANT: WareType = WareType(0x0000_0586);
pub const DEPOSIT: WareType = WareType(0x0000_0637);
pub const CULTIVATION_AREA: WareType = WareType(0x0000_07a3);
pub const OVERSEAS_MAIL: WareType = WareType(0x0000_09dc);
pub const CALAMARI: WareType = WareType(0x0000_1504);
pub const JALEA: WareType = WareType(0x0000_1505);
pub const ICE_CREAM: WareType = WareType(0x0000_1506);
pub const HERBS: WareType = WareType(0x0000_1507);
pub const NANDU_LEATHER: WareType = WareType(0x0000_1508);
pub const ORCHID: WareType = WareType(0x0000_150a);
pub const MOTOR: WareType = WareType(0x0000_150e);
pub const SCOOTER: WareType = WareType(0x0000_150f);
pub const MILK: WareType = WareType(0x0000_1509);
pub const FILM_REEL: WareType = WareType(0x0000_1510);
pub const FIRE_EXTINGUISHERS: WareType = WareType(0x0000_1511);
pub const POLICE_EQUIPMENT: WareType = WareType(0x0000_1512);
pub const FANS: WareType = WareType(0x0000_1513);
pub const MEDICINE: WareType = WareType(0x0000_1515);
pub const MINERALS: WareType = WareType(0x0000_1516);
pub const PIGMENTS: WareType = WareType(0x0000_1518);
pub const NANDU_FEATHERS: WareType = WareType(0x0000_1519);
pub const SOCCER_BALLS: WareType = WareType(0x0000_16ab);
pub const PERFUMES: WareType = WareType(0x0000_150c);
pub const COSTUMES: WareType = WareType(0x0000_150d);
pub const ELECTRIC_CABLES: WareType = WareType(0x0000_1888);
pub const MEZCAL: WareType = WareType(0x0000_19c8);
pub const DUNG: WareType = WareType(0x0000_60e7);
pub const FERTILIZER: WareType = WareType(0x0000_60e8);
pub const ATOLE: WareType = WareType(0x0000_622b);
pub const HOT_SAUCE: WareType = WareType(0x0000_63a2);
pub const CARIBOU_MEAT: WareType = WareType(0x0001_b836);
pub const BEAR_FUR: WareType = WareType(0x0001_b837);
pub const SEAL_SKIN: WareType = WareType(0x0001_b838);
pub const GOOSE_FEATHERS: WareType = WareType(0x0001_b839);
pub const HUSKIES: WareType = WareType(0x0001_b83a);
pub const WHALE_OIL: WareType = WareType(0x0001_b83b);
pub const PARKAS: WareType = WareType(0x0001_b83c);
pub const SLEEPIG_BAGS: WareType = WareType(0x0001_b83d);
pub const OIL_LAMPS: WareType = WareType(0x0001_b83e);
pub const HUSKY_SLEDS: WareType = WareType(0x0001_b83f);
pub const SLEDS: WareType = WareType(0x0001_b840);
pub const PEMMICAN: WareType = WareType(0x0001_b841);
pub const ARCTIC_GAS: WareType = WareType(0x0001_b842);
pub const WANZA_TIMBER: WareType = WareType(0x0001_beb4);
pub const SANGA_COW: WareType = WareType(0x0001_beb5);
pub const SALT: WareType = WareType(0x0001_beb6);
pub const DRIED_MEAT: WareType = WareType(0x0001_beb7);
pub const HIBISCUS_PETALS: WareType = WareType(0x0001_bebc);
pub const LINSEED: WareType = WareType(0x0001_bebd);
pub const TEFF: WareType = WareType(0x0001_bebf);
pub const INDIGO_DYE: WareType = WareType(0x0001_bec0);
pub const SPICES: WareType = WareType(0x0001_bec1);
pub const BEESWAX: WareType = WareType(0x0001_bec2);
pub const GOAT_MILK: WareType = WareType(0x0001_bec3);
pub const HIBISCUS_TEA: WareType = WareType(0x0001_bed6);
pub const LINEN: WareType = WareType(0x0001_bed7);
pub const FINERY: WareType = WareType(0x0001_bee1);
pub const MUD_BRICKS: WareType = WareType(0x0001_bee2);
pub const TAPESTRIES: WareType = WareType(0x0001_bee4);
pub const SPICED_FLOUR: WareType = WareType(0x0001_bee8);
pub const SEAFOOD_STEW: WareType = WareType(0x0001_beea);
pub const CLAY_PIPES: WareType = WareType(0x0001_beee);
pub const LEATHER_BOOTS: WareType = WareType(0x0001_befc);
pub const TAILORED_SUITS: WareType = WareType(0x0001_befe);
pub const TELEPHONES: WareType = WareType(0x0001_beff);
pub const ILLUMINATED_SCRIPT: WareType = WareType(0x0001_cbc2);
pub const LANTERNS: WareType = WareType(0x0001_cbc3);
pub const ORNATE_CANDLES: WareType = WareType(0x0001_cbc5);
pub const PAPER: WareType = WareType(0x0001_cbc6);
pub const CERAMICS: WareType = WareType(0x0001_cfc4);
pub const LOBSTER: WareType = WareType(0x0001_cfc8);
pub const WOOD: WareType = WareType(0x0001_d4c8);
pub const GRAPES: WareType = WareType(0x0001_d4ce);
pub const CHAMPAGNE: WareType = WareType(0x0001_d4d0);
pub const SPECTACLES: WareType = WareType(0x0001_d4de);
pub const COFFEE_BEANS: WareType = WareType(0x0001_d4df);
pub const COFFEE: WareType = WareType(0x0001_d4e0);
pub const FRIED_PLANTAINS: WareType = WareType(0x0001_d4e1);
pub const CORN: WareType = WareType(0x0001_d4e2);
pub const TORTILLAS: WareType = WareType(0x0001_d4e3);
pub const ALPACA_WOOL: WareType = WareType(0x0001_d4e4);
pub const BOMBINS: WareType = WareType(0x0001_d4e5);
pub const PLANTAINS: WareType = WareType(0x0001_d4e9);
pub const FISH_OIL: WareType = WareType(0x0001_d4ea);
pub const PONCHOS: WareType = WareType(0x0001_d4eb);
pub const FELT: WareType = WareType(0x0001_d4ec);
pub const CINNAMON: WareType = WareType(0x0002_07e5);
pub const COCONUT_OIL: WareType = WareType(0x0002_07e7);
pub const CITRUS: WareType = WareType(0x0002_07e9);
pub const SHAMPOO: WareType = WareType(0x0002_083d);
pub const JAM: WareType = WareType(0x0002_083f);
pub const LEMONADE: WareType = WareType(0x0002_0841);
pub const SOUVENIRS: WareType = WareType(0x0002_099c);
pub const CAMPHOR_WAX: WareType = WareType(0x0002_0dd8);
pub const ELEVATOR: WareType = WareType(0x0002_0ddf);
pub const RESIN: WareType = WareType(0x0002_0fae);
pub const CHERRY_WOOD: WareType = WareType(0x0002_0faf);
pub const LACQUER: WareType = WareType(0x0002_0fd9);
pub const ETHANOL: WareType = WareType(0x0002_0fda);
pub const CELLULOID: WareType = WareType(0x0002_0fee);
pub const CHEWING_GUM: WareType = WareType(0x0002_1012);
pub const BISCUITS: WareType = WareType(0x0002_103d);
pub const TYPEWRITER: WareType = WareType(0x0002_103e);
pub const TOYS: WareType = WareType(0x0002_103f);
pub const BILLIARD_TABLES: WareType = WareType(0x0002_1040);
pub const COGNAC: WareType = WareType(0x0002_1042);
pub const FUEL: WareType = WareType(0x0004_1eda);
pub const GRAIN: WareType = WareType(0x000f_6a10);
pub const BEEF: WareType = WareType(0x000f_6a11);
pub const HOPS: WareType = WareType(0x000f_6a12);
pub const POTATOES: WareType = WareType(0x000f_6a13);
pub const TIMBER: WareType = WareType(0x000f_6a14);
pub const WOOL: WareType = WareType(0x000f_6a15);
pub const RED_PEPPERS: WareType = WareType(0x000f_6a16);
pub const PIGS: WareType = WareType(0x000f_6a17);
pub const FISH: WareType = WareType(0x000f_6a18);
pub const CLAY: WareType = WareType(0x000f_6a19);
pub const REINFORCED_CONCRETE: WareType = WareType(0x000f_6a1a);
pub const SOAP: WareType = WareType(0x000f_6a1b);
pub const BRASS: WareType = WareType(0x000f_6a1c);
pub const BRICKS: WareType = WareType(0x000f_6a1d);
pub const SEWING_MACHINES: WareType = WareType(0x000f_6a1e);
pub const WINDOWS: WareType = WareType(0x000f_6a1f);
pub const LIGHT_BULBS: WareType = WareType(0x000f_6a20);
pub const FURS: WareType = WareType(0x000f_6a21);
pub const SAILS: WareType = WareType(0x000f_6a22);
pub const CHASSIS: WareType = WareType(0x000f_6a23);
pub const BREAD: WareType = WareType(0x000f_6a25);
pub const BEER: WareType = WareType(0x000f_6a26);
pub const FUR_COATS: WareType = WareType(0x000f_6a47);
pub const GRAMOPHONES: WareType = WareType(0x000f_6a48);
pub const GOLD: WareType = WareType(0x000f_6a49);
pub const GOULASH: WareType = WareType(0x000f_6a27);
pub const SCHNAPPS: WareType = WareType(0x000f_6a28);
pub const CANNED_FOOD: WareType = WareType(0x000f_6a29);
pub const STEEL_BEAMS: WareType = WareType(0x000f_6a2a);
pub const STEEL: WareType = WareType(0x000f_6a2b);
pub const WEAPONS: WareType = WareType(0x000f_6a2d);
pub const DYNAMITE: WareType = WareType(0x000f_6a2e);
pub const ADVANCED_WEAPONS: WareType = WareType(0x000f_6a2f);
pub const STEAM_MOTORS: WareType = WareType(0x000f_6a30);
pub const STEAM_CARRIAGES: WareType = WareType(0x000f_6a31);
pub const COAL: WareType = WareType(0x000f_6a32);
pub const IRON: WareType = WareType(0x000f_6a33);
pub const QUARTZ_SAND: WareType = WareType(0x000f_6a34);
pub const ZINC: WareType = WareType(0x000f_6a35);
pub const COPPER: WareType = WareType(0x000f_6a36);
pub const CEMENT: WareType = WareType(0x000f_6a37);
pub const SALTPETRE: WareType = WareType(0x000f_6a38);
pub const GOLD_ORE: WareType = WareType(0x000f_6a39);
pub const TALLOW: WareType = WareType(0x000f_6a3a);
pub const FLOUR: WareType = WareType(0x000f_6a3b);
pub const MALT: WareType = WareType(0x000f_6a3c);
pub const WORK_CLOTHES: WareType = WareType(0x000f_6a3d);
pub const SAUSAGES: WareType = WareType(0x000f_6a3e);
pub const SUGAR: WareType = WareType(0x000f_6a3f);
pub const COTTON_FABRIC: WareType = WareType(0x000f_6a40);
pub const GLASS: WareType = WareType(0x000f_6a41);
pub const WOOD_VENEERS: WareType = WareType(0x000f_6a42);
pub const FILAMENTS: WareType = WareType(0x000f_6a43);
pub const PENNY_FARTHINGS: WareType = WareType(0x000f_6a45);
pub const POCKET_WATCHES: WareType = WareType(0x000f_6a46);
pub const JEWELLERY: WareType = WareType(0x000f_6a4a);
pub const SUGAR_CANE: WareType = WareType(0x000f_6a4b);
pub const TOBACCO: WareType = WareType(0x000f_6a4c);
pub const COTTON: WareType = WareType(0x000f_6a4d);
pub const COCOA: WareType = WareType(0x000f_6a4e);
pub const CAOUTCHOUC: WareType = WareType(0x000f_6a4f);
pub const PEARLS: WareType = WareType(0x000f_6a50);
pub const RUM: WareType = WareType(0x000f_6a51);
pub const CHOCOLATE: WareType = WareType(0x000f_6a52);
pub const CIGARS: WareType = WareType(0x000f_6a53);
pub const OIL: WareType = WareType(0x000f_6b86);

impl Debug for WareType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&match *self {
            BLUEPRINT => "Blueprint".to_string(),
            LOCAL_MAIL => "Local Mail".to_string(),
            REGIONAL_MAIL => "Regional Mail".to_string(),
            BAUXITE => "Bauxite".to_string(),
            ALUMINIUM_PROFILES => "Aluminium Profiles".to_string(),
            HELIUM => "Helium".to_string(),
            WATER_DROP => "Water Drop".to_string(),
            BOMBS => "Bombs".to_string(),
            SEA_MINES => "Sea Mines".to_string(),
            PAMPHLETS => "Pamphlets".to_string(),
            CARE_PACKAGES => "Care Packages".to_string(),
            INDUSTRIAL_LUBRICANT => "Industrial Lubricant".to_string(),
            DEPOSIT => "Deposit".to_string(),
            CULTIVATION_AREA => "Cultivation Area".to_string(),
            OVERSEAS_MAIL => "Overseas Mail".to_string(),
            CALAMARI => "Calamari".to_string(),
            JALEA => "Jalea".to_string(),
            ICE_CREAM => "Ice Cream".to_string(),
            HERBS => "Herbs".to_string(),
            NANDU_LEATHER => "Nandu Leather".to_string(),
            ORCHID => "Orchid".to_string(),
            MOTOR => "Motor".to_string(),
            SCOOTER => "Scooter".to_string(),
            MILK => "Milk".to_string(),
            FILM_REEL => "Film Reel".to_string(),
            FIRE_EXTINGUISHERS => "Fire Extinguishers".to_string(),
            POLICE_EQUIPMENT => "Police Equipment".to_string(),
            FANS => "Fans".to_string(),
            MEDICINE => "Medicine".to_string(),
            MINERALS => "Minerals".to_string(),
            PIGMENTS => "Pigments".to_string(),
            NANDU_FEATHERS => "Nandu Feathers".to_string(),
            SOCCER_BALLS => "Soccer Balls".to_string(),
            PERFUMES => "Perfumes".to_string(),
            COSTUMES => "Costumes".to_string(),
            ELECTRIC_CABLES => "Electric Cables".to_string(),
            MEZCAL => "Mezcal".to_string(),
            DUNG => "Dung".to_string(),
            FERTILIZER => "Fertilizer".to_string(),
            ATOLE => "Atole".to_string(),
            HOT_SAUCE => "Hot Sauce".to_string(),
            CARIBOU_MEAT => "Caribou Meat".to_string(),
            BEAR_FUR => "Bear Fur".to_string(),
            SEAL_SKIN => "Seal Skin".to_string(),
            GOOSE_FEATHERS => "Goose Feathers".to_string(),
            HUSKIES => "Huskies".to_string(),
            WHALE_OIL => "Whale Oil".to_string(),
            PARKAS => "Parkas".to_string(),
            SLEEPIG_BAGS => "Sleeping Bags".to_string(),
            OIL_LAMPS => "Oil Lamps".to_string(),
            HUSKY_SLEDS => "Husky Sleds".to_string(),
            SLEDS => "Sleds".to_string(),
            PEMMICAN => "Pemmican".to_string(),
            ARCTIC_GAS => "Arctic Gas".to_string(),
            WANZA_TIMBER => "Wanza Timber".to_string(),
            SANGA_COW => "Sanga Cow".to_string(),
            SALT => "Salt".to_string(),
            DRIED_MEAT => "Dried Meat".to_string(),
            HIBISCUS_PETALS => "Hibicus Petals".to_string(),
            LINSEED => "Linseed".to_string(),
            TEFF => "Teff".to_string(),
            INDIGO_DYE => "Indigo Dye".to_string(),
            SPICES => "Spices".to_string(),
            BEESWAX => "Beeswax".to_string(),
            GOAT_MILK => "Goat Milk".to_string(),
            HIBISCUS_TEA => "Hibiscus Tea".to_string(),
            LINEN => "Linen".to_string(),
            FINERY => "Finery".to_string(),
            MUD_BRICKS => "Mud Bricks".to_string(),
            TAPESTRIES => "Tapestries".to_string(),
            SPICED_FLOUR => "Spiced Flour".to_string(),
            SEAFOOD_STEW => "Seafood Stew".to_string(),
            CLAY_PIPES => "Clay Pipes".to_string(),
            LEATHER_BOOTS => "Leather Boots".to_string(),
            TAILORED_SUITS => "Tailored Suits".to_string(),
            TELEPHONES => "Telephones".to_string(),
            ILLUMINATED_SCRIPT => "Illuminated Script".to_string(),
            LANTERNS => "Lanterns".to_string(),
            ORNATE_CANDLES => "Ornate Candles".to_string(),
            PAPER => "Paper".to_string(),
            CERAMICS => "Ceramics".to_string(),
            LOBSTER => "Lobster".to_string(),
            WOOD => "Wood".to_string(),
            GRAPES => "Grapes".to_string(),
            CHAMPAGNE => "Champagne".to_string(),
            SPECTACLES => "Spectacles".to_string(),
            COFFEE_BEANS => "Coffee Beans".to_string(),
            COFFEE => "Coffee".to_string(),
            FRIED_PLANTAINS => "Fried Plaintains".to_string(),
            CORN => "Corn".to_string(),
            TORTILLAS => "Tortillas".to_string(),
            ALPACA_WOOL => "Alpaca Wool".to_string(),
            BOMBINS => "Bombins".to_string(),
            PLANTAINS => "Plantains".to_string(),
            FISH_OIL => "Fish Oil".to_string(),
            PONCHOS => "Ponchos".to_string(),
            FELT => "Felt".to_string(),
            COCONUT_OIL => "Coconut Oil".to_string(),
            CITRUS => "Citrus".to_string(),
            SHAMPOO => "Shampoo".to_string(),
            JAM => "Jam".to_string(),
            LEMONADE => "Lemonade".to_string(),
            SOUVENIRS => "Souvenirs".to_string(),
            CAMPHOR_WAX => "Camphor Wax".to_string(),
            ELEVATOR => "Elevator".to_string(),
            RESIN => "Resin".to_string(),
            CHERRY_WOOD => "Cherry Wood".to_string(),
            LACQUER => "Lacquer".to_string(),
            ETHANOL => "Ethanol".to_string(),
            CELLULOID => "Celluloid".to_string(),
            CHEWING_GUM => "Chewing Gum".to_string(),
            BISCUITS => "Biscuits".to_string(),
            TYPEWRITER => "Typewriter".to_string(),
            TOYS => "Toys".to_string(),
            BILLIARD_TABLES => "Billiard Tables".to_string(),
            FUEL => "Fuel".to_string(),
            GRAIN => "Grain".to_string(),
            BEEF => "Beef".to_string(),
            HOPS => "Hops".to_string(),
            POTATOES => "Potatoes".to_string(),
            TIMBER => "Timber".to_string(),
            WOOL => "Wool".to_string(),
            RED_PEPPERS => "Red Peppers".to_string(),
            PIGS => "Pigs".to_string(),
            FISH => "Fish".to_string(),
            CLAY => "Clay".to_string(),
            REINFORCED_CONCRETE => "Reinforced Concrete".to_string(),
            SOAP => "Soap".to_string(),
            BRASS => "Brass".to_string(),
            BRICKS => "Bricks".to_string(),
            SEWING_MACHINES => "Sewing Machines".to_string(),
            WINDOWS => "Windows".to_string(),
            LIGHT_BULBS => "Light Bulbs".to_string(),
            FURS => "Furs".to_string(),
            SAILS => "Sails".to_string(),
            BREAD => "Bread".to_string(),
            BEER => "Beer".to_string(),
            FUR_COATS => "Fur".to_string(),
            GRAMOPHONES => "Gramophones".to_string(),
            GOLD => "Gold".to_string(),
            GOULASH => "Goulash".to_string(),
            SCHNAPPS => "Schnapps".to_string(),
            CANNED_FOOD => "Canned Food".to_string(),
            STEEL_BEAMS => "Steel Beams".to_string(),
            STEEL => "Steel".to_string(),
            WEAPONS => "Weapons".to_string(),
            DYNAMITE => "Dynamite".to_string(),
            ADVANCED_WEAPONS => "Advanced Weapons".to_string(),
            STEAM_MOTORS => "Steam Motors".to_string(),
            COAL => "Coal".to_string(),
            IRON => "Iron".to_string(),
            QUARTZ_SAND => "Quartz Sand".to_string(),
            ZINC => "Zinc".to_string(),
            COPPER => "Copper".to_string(),
            CEMENT => "Cement".to_string(),
            SALTPETRE => "Saltpetre".to_string(),
            GOLD_ORE => "Gold Ore".to_string(),
            TALLOW => "Tallow".to_string(),
            FLOUR => "Flour".to_string(),
            MALT => "Malt".to_string(),
            WORK_CLOTHES => "Work Clothes".to_string(),
            SAUSAGES => "Sausages".to_string(),
            SUGAR => "Sugar".to_string(),
            COTTON_FABRIC => "Cotton Fabric".to_string(),
            GLASS => "Glass".to_string(),
            WOOD_VENEERS => "Wood Veneers".to_string(),
            FILAMENTS => "Filaments".to_string(),
            PENNY_FARTHINGS => "Penny Farthings".to_string(),
            POCKET_WATCHES => "Pocket Watches".to_string(),
            JEWELLERY => "Jewellery".to_string(),
            SUGAR_CANE => "Sugar Cane".to_string(),
            TOBACCO => "Tobacco".to_string(),
            COTTON => "Cotton".to_string(),
            COCOA => "Cocoa".to_string(),
            CAOUTCHOUC => "Caoutchouc".to_string(),
            PEARLS => "Pearls".to_string(),
            RUM => "Rum".to_string(),
            CHOCOLATE => "Chocolate".to_string(),
            CIGARS => "Cigars".to_string(),
            OIL => "Oil".to_string(),
            _ => format!("Unknown({:#010x})", self.0),
        })
    }
}

impl From<WareType> for u32 {
    fn from(value: WareType) -> Self {
        value.0
    }
}
